[project]
name = "deep-agents"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "malik09-teach", email = "malikabbaskhan477@gmail.com" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
deep-agents = "deep_agents:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
